<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // 10 Data Kota Populer (is_popular = 1)
            [
                'name' => 'Jakarta',
                'slug' => 'jakarta',
                'description' => 'Ibu kota Indonesia yang merupakan pusat bisnis, politik, dan budaya.',
                'image' => '/images/jkt.jpg',
                'province' => 'DKI Jakarta',
                'order_index' => 1,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 542310,
            ],
            [
                'name' => 'Surabaya',
                'slug' => 'surabaya',
                'description' => 'Kota pahlawan dan pusat bisnis terbesar di Indonesia timur.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Timur',
                'order_index' => 2,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 421150,
            ],
            [
                'name' => 'Bandung',
                'slug' => 'bandung',
                'description' => 'Kota kembang dengan iklim sejuk dan pusat fashion serta kuliner yang terkenal.',
                'image' => '/images/mdn.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 3,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 398770,
            ],
            [
                'name' => 'Medan',
                'slug' => 'medan',
                'description' => 'Kota terbesar di Sumatera Utara yang terkenal dengan keberagaman budayanya.',
                'image' => '/images/jkt.jpg',
                'province' => 'Sumatera Utara',
                'order_index' => 4,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 312450,
            ],
            [
                'name' => 'Semarang',
                'slug' => 'semarang',
                'description' => 'Ibu kota Jawa Tengah dengan pesona kota lama dan kuliner khasnya.',
                'image' => '/images/ach.jpg',
                'province' => 'Jawa Tengah',
                'order_index' => 5,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 289100,
            ],
            [
                'name' => 'Makassar',
                'slug' => 'makassar',
                'description' => 'Gerbang Indonesia Timur yang terkenal dengan seafood dan sejarah Kerajaan Gowa.',
                'image' => '/images/pdg.jpg',
                'province' => 'Sulawesi Selatan',
                'order_index' => 6,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 254330,
            ],
            [
                'name' => 'Palembang',
                'slug' => 'palembang',
                'description' => 'Kota pempek yang terkenal dengan Jembatan Ampera dan sejarah kerajaan Sriwijaya.',
                'image' => '/images/mdn.jpg',
                'province' => 'Sumatera Selatan',
                'order_index' => 7,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 198500,
            ],
            [
                'name' => 'Tangerang',
                'slug' => 'tangerang',
                'description' => 'Kota industri dan perumahan terbesar di Provinsi Banten.',
                'image' => '/images/ach.jpg',
                'province' => 'Banten',
                'order_index' => 8,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 176200,
            ],
            [
                'name' => 'Depok',
                'slug' => 'depok',
                'description' => 'Kota penyangga Jakarta yang dikenal dengan sejumlah universitas ternama.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 9,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 165880,
            ],
            [
                'name' => 'Batam',
                'slug' => 'batam',
                'description' => 'Pusat industri dan perdagangan bebas yang dekat dengan Singapura dan Malaysia.',
                'image' => '/images/ach.jpg',
                'province' => 'Kepulauan Riau',
                'order_index' => 10,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 154900,
            ],

            // 5 Data Kota Tidak Populer (is_popular = 0)
            [
                'name' => 'Bogor',
                'slug' => 'bogor',
                'description' => 'Kota hujan dengan Kebun Raya yang terkenal dan destinasi wisata dekat Jakarta.',
                'image' => '/images/jkt.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 11,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 45200,
            ],
            [
                'name' => 'Pekanbaru',
                'slug' => 'pekanbaru',
                'description' => 'Ibu kota Provinsi Riau yang menjadi pusat perdagangan minyak dan kelapa sawit.',
                'image' => '/images/mdn.jpg',
                'province' => 'Riau',
                'order_index' => 12,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 38900,
            ],
            [
                'name' => 'Bandar Lampung',
                'slug' => 'bandar-lampung',
                'description' => 'Kota terbesar di Pulau Sumatera yang menjadi gerbang menuju Pulau Belitung.',
                'image' => '/images/pdg.jpg',
                'province' => 'Lampung',
                'order_index' => 13,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 31100,
            ],
            [
                'name' => 'Malang',
                'slug' => 'malang',
                'description' => 'Kota yang sejuk dan dikelilingi oleh pegunungan, terkenal dengan apel dan wisata alam.',
                'image' => '/images/ach.jpg',
                'province' => 'Jawa Timur',
                'order_index' => 14,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 27500,
            ],
            [
                'name' => 'Samarinda',
                'slug' => 'samarinda',
                'description' => 'Ibu kota Provinsi Kalimantan Timur yang terletak di tepi Sungai Mahakam.',
                'image' => '/images/jkt.jpg',
                'province' => 'Kalimantan Timur',
                'order_index' => 15,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 21900,
            ],

            // Tambahan Data Kota yang Hilang
            [
                'name' => 'Denpasar',
                'slug' => 'denpasar',
                'description' => 'Ibu kota Bali yang menjadi gerbang utama menuju pulau dewata dengan keindahan pantainya.',
                'image' => '/images/jkt.jpg',
                'province' => 'Bali',
                'order_index' => 16,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 345600,
            ],
            [
                'name' => 'Padang',
                'slug' => 'padang',
                'description' => 'Kota terbesar di Sumatera Barat yang terkenal dengan masakan Padang dan pantainya.',
                'image' => '/images/pdg.jpg',
                'province' => 'Sumatera Barat',
                'order_index' => 17,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 298700,
            ],
            [
                'name' => 'Yogyakarta',
                'slug' => 'yogyakarta',
                'description' => 'Kota budaya dan pendidikan dengan Keraton Yogyakarta dan dekat dengan Candi Borobudur.',
                'image' => '/images/ach.jpg',
                'province' => 'DI Yogyakarta',
                'order_index' => 18,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 412300,
            ],
            [
                'name' => 'Manado',
                'slug' => 'manado',
                'description' => 'Ibu kota Sulawesi Utara yang terkenal dengan Taman Nasional Bunaken dan kuliner seafoodnya.',
                'image' => '/images/pdg.jpg',
                'province' => 'Sulawesi Utara',
                'order_index' => 19,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 276500,
            ],
            [
                'name' => 'Mojokerto',
                'slug' => 'mojokerto',
                'description' => 'Kota bersejarah yang menjadi bagian dari wilayah Kerajaan Majapahit di masa lalu.',
                'image' => '/images/mdn.jpg',
                'province' => 'Jawa Timur',
                'order_index' => 20,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 38400,
            ],
            [
                'name' => 'Bali',
                'slug' => 'bali',
                'description' => 'Pulau dewata dengan pantai indah, budaya unik, dan destinasi wisata terkenal di dunia.',
                'image' => '/images/ach.jpg',
                'province' => 'Bali',
                'order_index' => 21,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 567800,
            ],
            [
                'name' => 'Mataram',
                'slug' => 'mataram',
                'description' => 'Ibu kota Provinsi Nusa Tenggara Barat yang menjadi gerbang menuju Pulau Lombok.',
                'image' => '/images/mdn.jpg',
                'province' => 'Nusa Tenggara Barat',
                'order_index' => 22,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 187600,
            ],
            [
                'name' => 'Demak',
                'slug' => 'demak',
                'description' => 'Kota bersejarah yang menjadi pusat penyebaran Islam di Jawa dengan Masjid Agung Demak.',
                'image' => '/images/jkt.jpg',
                'province' => 'Jawa Tengah',
                'order_index' => 23,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 29800,
            ],
        ];

        foreach ($cities as $data) {
            City::create($data);
        }

        $this->command->info('✅ Cities seeded successfully!');
    }
}
