<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // 10 Data Kota Populer (is_popular = 1)
            [
                'id' => 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
                'name' => 'Jakarta',
                'slug' => 'jakarta',
                'description' => 'Ibu kota Indonesia yang merupakan pusat bisnis, politik, dan budaya.',
                'image' => '/images/pdg.jpg',
                'province' => 'DKI Jakarta',
                'order_index' => 1,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 542310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
                'name' => 'Surabaya',
                'slug' => 'surabaya',
                'description' => 'Kota pahlawan dan pusat bisnis terbesar di Indonesia timur.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Timur',
                'order_index' => 2,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 421150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
                'name' => 'Bandung',
                'slug' => 'bandung',
                'description' => 'Kota kembang dengan iklim sejuk dan pusat fashion serta kuliner yang terkenal.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 3,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 398770,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
                'name' => 'Medan',
                'slug' => 'medan',
                'description' => 'Kota terbesar di Sumatera Utara yang terkenal dengan keberagaman budayanya.',
                'image' => '/images/jkt.jpg',
                'province' => 'Sumatera Utara',
                'order_index' => 4,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 312450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b',
                'name' => 'Semarang',
                'slug' => 'semarang',
                'description' => 'Ibu kota Jawa Tengah dengan pesona kota lama dan kuliner khasnya.',
                'image' => '/images/ach.jpg',
                'province' => 'Jawa Tengah',
                'order_index' => 5,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 289100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
                'name' => 'Makassar',
                'slug' => 'makassar',
                'description' => 'Gerbang Indonesia Timur yang terkenal dengan seafood dan sejarah Kerajaan Gowa.',
                'image' => '/images/pdg.jpg',
                'province' => 'Sulawesi Selatan',
                'order_index' => 6,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 254330,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d',
                'name' => 'Palembang',
                'slug' => 'palembang',
                'description' => 'Kota pempek yang terkenal dengan Jembatan Ampera dan sejarah kerajaan Sriwijaya.',
                'image' => '/images/pdg.jpg',
                'province' => 'Sumatera Selatan',
                'order_index' => 7,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 198500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e',
                'name' => 'Tangerang',
                'slug' => 'tangerang',
                'description' => 'Kota industri dan perumahan terbesar di Provinsi Banten.',
                'image' => '/images/pdg.jpg',
                'province' => 'Banten',
                'order_index' => 8,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 176200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f',
                'name' => 'Depok',
                'slug' => 'depok',
                'description' => 'Kota penyangga Jakarta yang dikenal dengan sejumlah universitas ternama.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 9,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 165880,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'd0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a',
                'name' => 'Batam',
                'slug' => 'batam',
                'description' => 'Pusat industri dan perdagangan bebas yang dekat dengan Singapura dan Malaysia.',
                'image' => '/images/ach.jpg',
                'province' => 'Kepulauan Riau',
                'order_index' => 10,
                'is_active' => true,
                'is_popular' => true,
                'views_count' => 154900,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 5 Data Kota Tidak Populer (is_popular = 0)
            [
                'id' => 'e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b',
                'name' => 'Bogor',
                'slug' => 'bogor',
                'description' => 'Kota hujan dengan Kebun Raya yang terkenal dan destinasi wisata dekat Jakarta.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Barat',
                'order_index' => 11,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 45200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c',
                'name' => 'Pekanbaru',
                'slug' => 'pekanbaru',
                'description' => 'Ibu kota Provinsi Riau yang menjadi pusat perdagangan minyak dan kelapa sawit.',
                'image' => '/images/pdg.jpg',
                'province' => 'Riau',
                'order_index' => 12,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 38900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d',
                'name' => 'Bandar Lampung',
                'slug' => 'bandar-lampung',
                'description' => 'Kota terbesar di Pulau Sumatera yang menjadi gerbang menuju Pulau Belitung.',
                'image' => '/images/pdg.jpg',
                'province' => 'Lampung',
                'order_index' => 13,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 31100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e',
                'name' => 'Malang',
                'slug' => 'malang',
                'description' => 'Kota yang sejuk dan dikelilingi oleh pegunungan, terkenal dengan apel dan wisata alam.',
                'image' => '/images/pdg.jpg',
                'province' => 'Jawa Timur',
                'order_index' => 14,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 27500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f',
                'name' => 'Samarinda',
                'slug' => 'samarinda',
                'description' => 'Ibu kota Provinsi Kalimantan Timur yang terletak di tepi Sungai Mahakam.',
                'image' => '/images/pdg.jpg',
                'province' => 'Kalimantan Timur',
                'order_index' => 15,
                'is_active' => true,
                'is_popular' => false,
                'views_count' => 21900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('cities')->insert($cities);
    }
}
