<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ebook;
use App\Models\Category;
use App\Models\City;
use App\Models\User;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class EbookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ebooks = [
            [
                'id' => '44f72995-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'slug' => 'clean-code-handbook-agile-software-craftsmanship',
                'description' => 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn\'t have to be that way.',
                'short_description' => 'Buku wajib untuk programmer yang ingin menulis kode yang bersih, mudah dipahami, dan mudah di-maintain.',
                'author' => 'Robert C. Martin',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQxdrfnY3jF-G_oCs9EmrBDOptIsqnhJsTzoUBG7ggF7KftSfeVcCtKVt-pRCULCTZPXs&usqp=CAU',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/clean-code.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 890,
                'average_rating' => 4.80,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 2, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f929d0-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Midnight Library',
                'slug' => '-midnight-library',
                'description' => 'Between life and death there is a library, and within that library, shelves go on forever. Every book provides a chance to try another life you could have lived.',
                'short_description' => 'Novel tentang seorang wanita yang menemukan perpustakaan antara hidup dan mati.',
                'author' => 'Matt Haig',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDyURiRkAyR8M19wt-aAvUy8ZCXXS_z2mv0w&s',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/midnight-library.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2100,
                'average_rating' => 4.50,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 10, 18, 1, 5, 7),
                'created_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f9495b-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
                'slug' => 'atomic-habits-build-good-habits-break-bad-ones',
                'description' => 'A supremely practical and useful book. James Clear distills the most fundamental information about habit formation, so you can accomplish more by focusing on less.',
                'short_description' => 'Buku tentang membangun kebiasaan kecil yang menghasilkan perubahan besar.',
                'author' => 'James Clear',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg',
                // 'content_text' => null,
                'pdf_file' => 'https://eprints.upgris.ac.id/385/1/Aku%2C%20Dia%20dan%20Mereka%20Cover%20Full.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 4,
                'read_count' => 3800,
                'average_rating' => 4.90,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 17, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 9, 3, 4, 49),
            ],
            [
                'id' => '44f94d4f-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Pragmatic Programmer: Your Journey to Mastery',
                'slug' => 'pragmatic-programmer-journey-to-mastery',
                'description' => 'This book is for programmers who want to become software craftsmen. This isn\'t just another programming book; it\'s a guide to becoming a better, more pragmatic programmer.',
                'short_description' => 'Panduan untuk menjadi programmer yang pragmatis dan efektif.',
                'author' => 'David Thomas, Andrew Hunt',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/51W1sBPO7tL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/pragmatic-programmer.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 540,
                'average_rating' => 4.70,
                'total_reviews' => 134,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 22, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 23, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f95087-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'description' => 'In this book, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.',
                'short_description' => 'Eksplorasi tentang dua sistem pemikiran manusia.',
                'author' => 'Daniel Kahneman',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/61fdrEuPJwL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/thinking-fast-slow.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1500,
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'created_at' => Carbon::create(2025, 8, 4, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f95374-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Laut Bercerita',
                'slug' => 'laut-bercerita',
                'description' => 'Ketika Dira, seorang aktivis mahasiswa, menghilang secara misterius di tengah gejolak politik masa lalu, keluarganya hanya menerima keheningan sebagai jawaban. Bertahun-tahun kemudian, sang adik, Lira, tumbuh dengan bayang-bayang ketidakpastian. Didorong oleh kenangan dan teka-teki yang tertinggal, Lira memulai pencarian akan kebenaran. Melalui catatan lama, saksi bisu, dan potongan sejarah yang tersembunyi, ia mencoba menyusun kembali jejak sang kakak — dan menghadapi kenyataan pahit tentang negara, keluarga, dan dirinya sendiri.',
                'short_description' => 'Novel masterpiece dari Leila S. Chudori tentang sejarah kelam Indonesia.',
                'author' => 'Leila S. Chudori',
                'cover_image' => 'https://cdn.gramedia.com/uploads/items/9786024246945_Laut-Bercerita.jpg',
                // 'content_text' => null,
                'pdf_file' => '/images/testing.pdf',
                'language' => 'id',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 13,
                'read_count' => 3200,
                'average_rating' => 4.80,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 8, 4, 1, 5, 7),
                'created_at' => Carbon::create(2025, 6, 5, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 8, 4, 25, 14),
            ],
            [
                'id' => '44f95637-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Pemrograman Python: Dasar hingga Mahir',
                'slug' => 'pemrograman-python-dasar-hingga-mahir',
                'description' => 'Buku komprehensif untuk belajar Python dari dasar hingga tingkat lanjut dengan contoh praktis.',
                'short_description' => 'Buku wajib untuk belajar Python dengan pendekatan praktis.',
                'author' => 'Budi Raharjo',
                'cover_image' => 'https://cdn.gramedia.com/uploads/products/lnl19y9apu.jpg',
                // 'content_text' => 'Buku ini mengajarkan Python dari konsep dasar hingga pembuatan aplikasi real.',
                'pdf_file' => '/pdfs/python-pemrograman.pdf',
                'language' => 'id',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2100,
                'average_rating' => 4.50,
                'total_reviews' => 234,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 12, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 13, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96603-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'A Brief History of Time',
                'slug' => 'a-brief-history-of-time',
                'description' => 'From the Big Bang to Black Holes, Stephen Hawking explains the universe in a way that is accessible to everyone.',
                'short_description' => 'Perjalanan melalui kosmos dari salah satu pemikir terbesar abad kita.',
                'author' => 'Stephen Hawking',
                'cover_image' => 'https://m.media-amazon.com/images/I/81DBK93b6jL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/brief-history-time.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 80,
                'average_rating' => 4.70,
                'total_reviews' => 89,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 9, 50, 12),
                'created_at' => Carbon::create(2025, 11, 2, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96951-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Digital Marketing Fundamentals',
                'slug' => 'digital-marketing-fundamentals',
                'description' => 'Learn the basics of digital marketing in the modern era. SEO, Social Media, Content Marketing, and more.',
                'short_description' => 'Panduan dasar digital marketing untuk pemula.',
                'author' => 'Marketing Team',
                'cover_image' => 'https://i0.wp.com/minhajpustaka.id/wp-content/uploads/2025/05/COVER-4-scaled.png?fit=1729%2C2560&ssl=1',
                // 'content_text' => 'Full content available in text format.',
                'pdf_file' => null,
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.40,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 27, 1, 5, 7),
                'created_at' => Carbon::create(2025, 11, 17, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96c10-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Design of Everyday Things',
                'slug' => 'design-everyday-things',
                'description' => 'Even the smartest among us can feel inept as we fail to figure out which light switch or oven burner to turn on.',
                'short_description' => 'Buku klasik tentang design dan user experience.',
                'author' => 'Don Norman',
                'cover_image' => 'https://m.media-amazon.com/images/I/71sF8kuMW3L._AC_UF1000,1000_QL80_.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/design-everyday-things.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1200,
                'average_rating' => 4.60,
                'total_reviews' => 156,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'created_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab38443d-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Eloquent JavaScript',
                'slug' => 'eloquent-javascript',
                'description' => 'A modern introduction to programming with JavaScript.',
                'short_description' => 'Buku JavaScript terbaik untuk pemula hingga mahir.',
                'author' => 'Marijn Haverbeke',
                'cover_image' => 'https://eloquentjavascript.net/img/cover.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/eloquent-js.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1200,
                'average_rating' => 4.70,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 27, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44ac4f-cf2e-11f0-9073-745d2258e25c',
                'title' => 'You Don\'t Know JS Yet',
                'slug' => 'you-dont-know-js-yet',
                'description' => 'Deep dive into JavaScript core mechanisms.',
                'short_description' => 'Seri lengkap pengenalan mendalam JavaScript.',
                'author' => 'Kyle Simpson',
                'cover_image' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1585414018i/52764087.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/ydkjs.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1800,
                'average_rating' => 4.80,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 22, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44b4bc-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Clean Coder',
                'slug' => '-clean-coder',
                'description' => 'A code of conduct for professional programmers.',
                'short_description' => 'Panduan menjadi programmer profesional.',
                'author' => 'Robert C. Martin',
                'cover_image' => 'https://m.media-amazon.com/images/I/51RjrmLJv0L.__AC_SR166,182___.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/clean-coder.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 650,
                'average_rating' => 4.60,
                'total_reviews' => 123,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 17, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44b872-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Design Patterns: Elements of Reusable Object-Oriented Software',
                'slug' => 'design-patterns',
                'description' => 'The classic book on design patterns.',
                'short_description' => 'Buku klasik tentang design patterns.',
                'author' => 'Erich Gamma',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/51szD9HC9pL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/design-patterns.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 900,
                'average_rating' => 4.90,
                'total_reviews' => 267,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 12, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44bb0c-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Refactoring: Improving the Design of Existing Code',
                'slug' => 'refactoring-improving-design',
                'description' => 'How to improve existing code structure.',
                'short_description' => 'Teknik refactoring untuk kode yang lebih baik.',
                'author' => 'Martin Fowler',
                'cover_image' => 'https://m.media-amazon.com/images/I/71vEr0oyt-L._AC_UF1000,1000_QL80_.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/refactoring.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 720,
                'average_rating' => 4.70,
                'total_reviews' => 156,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 7, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44bf32-cf2e-11f0-9073-745d2258e25c',
                'title' => '1984',
                'slug' => '1984-george-orwell',
                'description' => 'Classic dystopian novel by George Orwell.',
                'short_description' => 'Novel dystopian klasik tentang masa depan.',
                'author' => 'George Orwell',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/1984.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.80,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 2, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c21c-cf2e-11f0-9073-745d2258e25c',
                'title' => 'To Kill a Mockingbird',
                'slug' => 'to-kill-a-mockingbird',
                'description' => 'Pulitzer Prize-winning novel.',
                'short_description' => 'Novel pemenang Pulitzer Prize.',
                'author' => 'Harper Lee',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81aY1lxk+9L.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/mockingbird.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3200,
                'average_rating' => 4.90,
                'total_reviews' => 489,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 28, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c4df-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Great Gatsby',
                'slug' => '-great-gatsby',
                'description' => 'American classic novel.',
                'short_description' => 'Klasik sastra Amerika.',
                'author' => 'F. Scott Fitzgerald',
                'cover_image' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/512t1zz2t2.jpeg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/gatsby.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2700,
                'average_rating' => 4.70,
                'total_reviews' => 345,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 23, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c748-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Pride and Prejudice',
                'slug' => 'pride-and-prejudice',
                'description' => 'Romantic novel of manners.',
                'short_description' => 'Novel romantis klasik.',
                'author' => 'Jane Austen',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71Q1tPupKjL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/pride-prejudice.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2400,
                'average_rating' => 4.80,
                'total_reviews' => 412,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 18, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c9d3-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Hobbit',
                'slug' => '-hobbit',
                'description' => 'Fantasy novel by J.R.R. Tolkien.',
                'short_description' => 'Novel fantasi petualangan Bilbo Baggins.',
                'author' => 'J.R.R. Tolkien',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/hobbit.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3500,
                'average_rating' => 4.90,
                'total_reviews' => 523,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 13, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44ce24-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Rich Dad Poor Dad',
                'slug' => 'rich-dad-poor-dad',
                'description' => 'Financial literacy and independence.',
                'short_description' => 'Mengubah mindset tentang uang dan investasi.',
                'author' => 'Robert Kiyosaki',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/rich-dad.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4500,
                'average_rating' => 4.60,
                'total_reviews' => 678,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 8, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d0f6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The 7 Habits of Highly Effective People',
                'slug' => '7-habits-highly-effective-people',
                'description' => 'Personal and professional effectiveness.',
                'short_description' => '7 kebiasaan orang-orang efektif.',
                'author' => 'Stephen R. Covey',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp4yXo-iLBeG2yNDazs9yS9VxZh-xB8N1FJA&s',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/7-habits.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4200,
                'average_rating' => 4.70,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 3, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d460-cf2e-11f0-9073-745d2258e25c',
                'title' => 'How to Win Friends and Influence People',
                'slug' => 'how-to-win-friends',
                'description' => 'Self-help book about social skills.',
                'short_description' => 'Cara berhubungan dengan orang lain.',
                'author' => 'Dale Carnegie',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71tbalAHYCL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/win-friends.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4800,
                'average_rating' => 4.80,
                'total_reviews' => 612,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 28, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d6ec-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'slug' => 'subtle-art-not-giving-fck',
                'description' => 'Counterintuitive approach to living.',
                'short_description' => 'Pendekatan hidup yang berbeda.',
                'author' => 'Mark Manson',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/subtle-art.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 5400,
                'average_rating' => 4.50,
                'total_reviews' => 734,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 23, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d97e-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Deep Work: Rules for Focused Success',
                'slug' => 'deep-work',
                'description' => 'Rules for focused success in a distracted world.',
                'short_description' => 'Cara fokus di dunia yang penuh gangguan.',
                'author' => 'Cal Newport',
                'cover_image' => 'https://m.media-amazon.com/images/I/61zt25yYrCL._AC_UF1000,1000_QL80_.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/deep-work.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2900,
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 18, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44faf6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Mythical Man-Month',
                'slug' => 'mythical-man-month',
                'description' => 'Essays on software engineering.',
                'short_description' => 'Esai tentang engineering software.',
                'author' => 'Fred Brooks',
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/f/fd/Mythical_man-month_%28book_cover%29.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/mythical-man-month.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1400,
                'average_rating' => 4.80,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 13, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44fe95-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Introduction to Algorithms',
                'slug' => 'introduction-algorithms',
                'description' => 'Comprehensive textbook on algorithms.',
                'short_description' => 'Buku lengkap tentang algoritma.',
                'author' => 'Thomas H. Cormen',
                'cover_image' => 'https://g.sdlcdn.com/imgs/k/f/6/INTRODUCTION-TO-ALGORITHMS-by-Thomas-SDL369742066-1-96985.jpg?trim=10&w=590&h=695&sharp=7',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/algorithms.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1600,
                'average_rating' => 4.90,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 8, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450121-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Selfish Gene',
                'slug' => 'selfish-gene',
                'description' => 'Evolutionary biology book.',
                'short_description' => 'Buku biologi evolusioner.',
                'author' => 'Richard Dawkins',
                'cover_image' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1366758096i/61535.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/selfish-gene.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2400,
                'average_rating' => 4.70,
                'total_reviews' => 312,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 3, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4503f6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Sapiens: A Brief History of Humankind',
                'slug' => 'sapiens-brief-history-humankind',
                'description' => 'History of the human species.',
                'short_description' => 'Sejarah spesies manusia.',
                'author' => 'Yuval Noah Harari',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/sapiens.pdf',
                'language' => 'en',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 5900,
                'average_rating' => 4.80,
                'total_reviews' => 789,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 29, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab45069e-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Cosmos',
                'slug' => 'cosmos',
                'description' => 'Popular science book about the universe.',
                'short_description' => 'Buku sains populer tentang alam semesta.',
                'author' => 'Carl Sagan',
                'cover_image' => 'https://m.media-amazon.com/images/I/51SX54fcT-L._AC_UF1000,1000_QL80_.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/cosmos.pdf',
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2700,
                'average_rating' => 4.90,
                'total_reviews' => 412,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 24, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450945-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Ronggeng Dukuh Paruk',
                'slug' => 'ronggeng-dukuh-paruk',
                'description' => 'Novel karya Ahmad Tohari.',
                'short_description' => 'Kisah tentang kehidupan penari ronggeng.',
                'author' => 'Ahmad Tohari',
                'cover_image' => 'https://ebooks.gramedia.com/ebook-covers/53333/image_highres/BLK_RDP2020706247.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/ronggeng-dukuh-paruk.pdf',
                'language' => 'id',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2800,
                'average_rating' => 4.70,
                'total_reviews' => 234,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 19, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450bba-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Negeri 5 Menara',
                'slug' => 'negeri-5-menara',
                'description' => 'Novel inspiratif tentang pesantren.',
                'short_description' => 'Kisah inspiratif kehidupan pesantren.',
                'author' => 'Ahmad Fuadi',
                'cover_image' => 'https://assets-a1.kompasiana.com/items/album/2015/08/15/foto-55cf1f2ec423bd1608ecc805.jpg',
                // 'content_text' => null,
                'pdf_file' => '/pdfs/negeri-5-menara.pdf',
                'language' => 'id',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3900,
                'average_rating' => 4.80,
                'total_reviews' => 345,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 14, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450e38-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Laskar Pelangi',
                'slug' => 'laskar-pelangi',
                'description' => 'Novel karya Andrea Hirata.',
                'short_description' => 'Kisah tentang pendidikan dan persahabatan.',
                'author' => 'Andrea Hirata',
                'cover_image' => 'https://simpus.mkri.id/uploaded_files/sampul_koleksi/original/Monograf//uploadedfiles/perpustakaan/11610-11613.jpg',
                // 'content_text' => null,
                'pdf_file' => '/images/sampel-2.pdf',
                'language' => 'id',
                // 'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 6800,
                'average_rating' => 4.90,
                'total_reviews' => 890,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 9, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4513ef-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Web Development Basics',
                'slug' => 'web-development-basics',
                'description' => 'Introduction to web development.',
                'short_description' => 'Pengantar dasar web development.',
                'author' => 'Web Team',
                'cover_image' => 'https://m.media-amazon.com/images/I/61E2+k4+uRL._AC_UF1000,1000_QL80_.jpg',
                // 'content_text' => 'Full HTML, CSS, JavaScript content.',
                'pdf_file' => null,
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.40,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 4, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4516f0-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Data Science Fundamentals',
                'slug' => 'data-science-fundamentals',
                'description' => 'Introduction to data science.',
                'short_description' => 'Dasar-dasar data science untuk pemula.',
                'author' => 'Data Team',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTiQWQgvVsTlfLIikfL74aQnQsS5MGlCvL1A&s',
                // 'content_text' => 'Python, statistics, machine learning basics.',
                'pdf_file' => null,
                'language' => 'en',
                // 'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3400,
                'average_rating' => 4.50,
                'total_reviews' => 167,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 30, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
        ];// Ambil ID dari data master yang sudah ada
        $creatorId = DB::table('users')->where('email', 'like', '%creator%')->inRandomOrder()->value('id');
        $categoryId = DB::table('categories')->inRandomOrder()->value('id');
        $cityId = DB::table('cities')->inRandomOrder()->value('id');

        $ebooks = [
            [
                'id' => 'e7a1b2c3-d4e5-f6g7-h8i9-j0k1l2m3n4o',
                'title' => 'The Pragmatic Programmer: Your Journey to Mastery',
                'slug' => 'pragmatic-programmer-journey-mastery',
                'description' => 'Written as a series of self-contained sections and filled with classic and fresh anecdotes, thoughtful examples, and interesting analogies, The Pragmatic Programmer illustrates the best approaches and major pitfalls of many different software development environments.',
                'short_description' => 'A guide to becoming a better, more pragmatic programmer.',
                'author' => 'David Thomas, Andrew Hunt',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/51W1sBPO7tL.jpg',
                'pdf_file' => '/pdfs/pragmatic-programmer.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 156,
                'view_count' => 0,
                'read_count' => 720,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 7, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'f5g6h7i8-j9k0-l1m2-n3o4-p5q6r7s8t9u',
                'title' => 'Deep Work: Rules for Focused Success in a Distracted World',
                'slug' => 'deep-work-rules-for-focused-success',
                'description' => 'Deep work is the ability to focus without distraction on a cognitively demanding task. It\'s a skill that allows you to quickly master complicated information and produce better results in less time.',
                'short_description' => 'How to master the skill of deep work in a distracted world.',
                'author' => 'Cal Newport',
                'cover_image' => 'https://m.media-amazon.com/images/I/61zt25yYrCL._AC_UF1000,1000_QL80_.jpg',
                'pdf_file' => '/pdfs/deep-work.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'view_count' => 0,
                'read_count' => 2900,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 18, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 14, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6',
                'title' => 'Sapiens: A Brief History of Humankind',
                'slug' => 'sapiens-brief-history-of-humankind',
                'description' => 'From a renowned historian comes a groundbreaking narrative of humanity\'s creation and evolution that explores the ways in which biology and history have defined us.',
                'short_description' => 'A brief history of the human species from the Stone Age to the present.',
                'author' => 'Yuval Noah Harari',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg',
                'pdf_file' => '/pdfs/sapiens.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 789,
                'view_count' => 0,
                'read_count' => 5900,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 29, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 25, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'b2c3d4e5-f6g7-h8i9-j0k1-l2m3n4o5p6q7',
                'title' => 'Laskar Pelangi',
                'slug' => 'laskar-pelangi',
                'description' => 'Novel yang menceritakan kisah hidup 10 anak dari keluarga miskin yang bersekolah di SD Muhammadiyah di Belitung. Mereka dijuluki "Laskar Pelangi" karena kekompakan dan semangat mereka.',
                'short_description' => 'Kisah inspiratif tentang persahabatan dan pendidikan di Belitung.',
                'author' => 'Andrea Hirata',
                'cover_image' => 'https://simpus.mkri.id/uploaded_files/sampul_koleksi/original/Monograf//uploadedfiles/perpustakaan/11610-11613.jpg',
                'pdf_file' => '/pdfs/laskar-pelangi.pdf',
                'language' => 'id',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 890,
                'view_count' => 0,
                'read_count' => 6800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 9, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 5, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'c3d4e5f6-g7h8-i9j0-k1l2-m3n4o5p6q7r8',
                'title' => 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
                'slug' => 'atomic-habits-easy-proven-way',
                'description' => 'No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
                'short_description' => 'Tiny changes, remarkable results. An easy & proven way to build good habits.',
                'author' => 'James Clear',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg',
                'pdf_file' => '/pdfs/atomic-habits.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 567,
                'view_count' => 0,
                'read_count' => 3800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 11, 17, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 13, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'd4e5f6g7-h8i9-j0k1-l2m3-n4o5-p6q7-r8s9-t0u1',
                'title' => 'The Psychology of Money',
                'slug' => 'psychology-of-money',
                'description' => 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. The Psychology of Money is a book about human behavior and the weird ways we think about money.',
                'short_description' => 'Timeless lessons on wealth, greed, and happiness doing well with money.',
                'author' => 'Morgan Housel',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTymThxDkwzaCF4DmJEgEBV8SnDawddZchOJA&s',
                'pdf_file' => '/pdfs/psychology-of-money.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.75,
                'total_reviews' => 445,
                'view_count' => 0,
                'read_count' => 3100,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 5, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'e5f6g7h8-i9j0-k1l2-m3n4-o5p6-q7r8-s9t0-u1v2',
                'title' => 'Ronggeng Dukuh Paruk',
                'slug' => 'ronggeng-dukuh-paruk',
                'description' => 'Novel yang mengisahkan kehidupan seorang penari ronggeng bernama Srintil yang hidup di Dukuh Paruk. Novel ini mengangkat isu-isu sosial, politik, dan budaya masyarakat pedesaan di Indonesia pada masa lalu.',
                'short_description' => 'Kisah kehidupan penari ronggeng di Dukuh Paruk yang penuh dengan isu sosial.',
                'author' => 'Ahmad Tohari',
                'cover_image' => 'https://ebooks.gramedia.com/ebook-covers/53333/image_highres/BLK_RDP2020706247.jpg',
                'pdf_file' => '/pdfs/ronggeng-dukuh-paruk.pdf',
                'language' => 'id',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 234,
                'view_count' => 0,
                'read_count' => 2800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 19, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 15, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'f6g7h8i9-j0k1-l2m3-n4o5-p6q7-r8s9-t0u1-v2w3',
                'title' => 'The Lean Startup: How Today\'s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses',
                'slug' => 'lean-startup-continuous-innovation',
                'description' => 'The Lean Startup provides a scientific approach to creating and managing successful startups in an age when companies have to be more agile than ever.',
                'short_description' => 'How to use continuous innovation to create successful businesses.',
                'author' => 'Eric Ries',
                'cover_image' => 'https://m.media-amazon.com/images/I/71sxTeZIi6L._AC_UF1000,1000_QL80_.jpg',
                'pdf_file' => '/pdfs/lean-startup.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.65,
                'total_reviews' => 398,
                'view_count' => 0,
                'read_count' => 2500,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 25, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 21, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'g7h8i9j0-k1l2-m3n4-o5p6-q7r8-s9t0-u1v2-w3x4',
                'title' => 'Cosmos',
                'slug' => 'cosmos',
                'description' => 'Cosmos is one of the bestselling science books of all time. In clear-eyed prose, Sagan reveals a jewel-like blue world inhabited by a life form that is just beginning to discover its own identity.',
                'short_description' => 'A personal voyage to the heart of the universe and the meaning of life.',
                'author' => 'Carl Sagan',
                'cover_image' => 'https://m.media-amazon.com/images/I/51SX54fcT-L._AC_UF1000,1000_QL80_.jpg',
                'pdf_file' => '/pdfs/cosmos.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 412,
                'view_count' => 0,
                'read_count' => 2700,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 24, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 20, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'h8i9j0k1-l2m3-n4o5-p6q7-r8s9-t0u1-v2w3-x4y5',
                'title' => 'Negeri 5 Menara',
                'slug' => 'negeri-5-menara',
                'description' => 'Novel ini mengisahkan perjalanan Alif enam tahun pertama di Pondok Madani. Alif bertemu dengan teman-teman dari berbagai daerah di Indonesia yang memiliki latar belakang dan karakter yang beragam.',
                'short_description' => 'Kisah inspiratif tentang kehidupan di pesantren dan persahabatan.',
                'author' => 'Ahmad Fuadi',
                'cover_image' => 'https://assets-a1.kompasiana.com/items/album/2015/08/15/foto-55cf1f2ec423bd1608ecc805.jpg',
                'pdf_file' => '/pdfs/negeri-5-menara.pdf',
                'language' => 'id',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 345,
                'view_count' => 0,
                'read_count' => 3900,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 14, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 10, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'i9j0k1l2-m3n4-o5p6-q7r8-s9t0-u1v2-w3x4-y5z6',
                'title' => 'The Design of Everyday Things: Revised and Expanded Edition',
                'slug' => 'design-of-everyday-things-revised',
                'description' => 'Even the smartest among us can feel inept as we fail to figure out the light switch, stove, or refrigerator. In this brilliant book, Don Norman shows that design is not just about looks, but also about usability.',
                'short_description' => 'A book about the psychology of everyday things and how design should work.',
                'author' => 'Don Norman',
                'cover_image' => 'https://m.media-amazon.com/images/I/71sF8kuMW3L._AC_UF1000,1000_QL80_.jpg',
                'pdf_file' => '/pdfs/design-everyday-things.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.60,
                'total_reviews' => 156,
                'view_count' => 0,
                'read_count' => 1200,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 3, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'j0k1l2m3-n4o5-p6q7-r8s9-t0u1-v2w3-x4y5-z6a7',
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'description' => 'In the highly anticipated Thinking, Fast and Slow, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think and make choices.',
                'short_description' => 'Exploring the two systems that drive the way we think and make decisions.',
                'author' => 'Daniel Kahneman',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/61fdrEuPJwL.jpg',
                'pdf_file' => '/pdfs/thinking-fast-slow.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'view_count' => 0,
                'read_count' => 1500,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 8, 4, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'k1l2m3n4-o5p6-q7r8-s9t0-u1v2-w3x4-y5z6-a7b8',
                'title' => 'You Don\'t Know JS Yet: Get Started',
                'slug' => 'you-dont-know-js-yet-get-started',
                'description' => 'It seems like there\'s never been a better time to learn JavaScript. This book provides a solid foundation for anyone looking to learn this popular programming language.',
                'short_description' => 'A deep dive into the core mechanisms of the JavaScript language.',
                'author' => 'Kyle Simpson',
                'cover_image' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1585414018i/52764087.jpg',
                'pdf_file' => '/pdfs/ydkjs.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 245,
                'view_count' => 0,
                'read_count' => 1800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 11, 22, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 18, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'l2m3n4o5-p6q7-r8s9-t0u1-v2w3-x4y5-z6a7-b8c9',
                'title' => 'Rich Dad Poor Dad: What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
                'slug' => 'rich-dad-poor-dad',
                'description' => 'Robert Kiyosaki’s easy-to-understand, and compelling story about financial literacy is one of the all-time bestsellers in the personal finance field.',
                'short_description' => 'What the rich teach their kids about money that the poor and middle class do not.',
                'author' => 'Robert T. Kiyosaki',
                'cover_image' => 'https://m.media-amazon.com/images/I/81BE7eeKzAL._AC_UF1000,1000_QL80_.jpg',
                'pdf_file' => '/images/sampel-1.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.60,
                'total_reviews' => 678,
                'view_count' => 0,
                'read_count' => 4500,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 8, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 4, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'm3n4o5p6-q7r8-s9t0-u1v2-w3x4-y5z6-a7b8-c9d0',
                'title' => 'The 7 Habits of Highly Effective People',
                'slug' => '7-habits-highly-effective-people',
                'description' => 'Stephen Covey\'s book, The 7 Habits of Highly Effective People, has been a top seller for the simple reason that it ignores trends and pop psychology and focuses on timeless principles of fairness, integrity, honesty, and human dignity.',
                'short_description' => 'Powerful lessons in personal change and professional success.',
                'author' => 'Stephen R. Covey',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp4yXo-iLBeG2yNDazs9yS9VxZh-xB8N1FJA&s',
                'pdf_file' => '/pdfs/7-habits.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 567,
                'view_count' => 0,
                'read_count' => 4200,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 3, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'n4o5p6q7-r8s9-t0u1-v2w3-x4y5-z6a7-b8c9-d0e1',
                'title' => 'How to Win Friends and Influence People',
                'slug' => 'how-to-win-friends-and-influence-people',
                'description' => 'For more than sixty years the rock-solid, time-tested advice in this book has carried thousands of now famous people up the ladder of success in their business and personal lives.',
                'short_description' => 'The only book you need to lead you to success in your business and personal life.',
                'author' => 'Dale Carnegie',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71tbalAHYCL.jpg',
                'pdf_file' => '/pdfs/win-friends.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 612,
                'view_count' => 0,
                'read_count' => 4800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 28, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 24, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'o5p6q7r8-s9t0-u1v2-w3x4-y5z6-a7b8-c9d0-e1f2',
                'title' => 'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life',
                'slug' => 'subtle-art-of-not-giving-a-fck',
                'description' => 'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be "positive" all the time so that we can truly become better, happier people.',
                'short_description' => 'A counterintuitive approach to living a good life that has captivated millions.',
                'author' => 'Mark Manson',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg',
                'pdf_file' => '/pdfs/subtle-art.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.50,
                'total_reviews' => 734,
                'view_count' => 0,
                'read_count' => 5400,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 23, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 19, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'p6q7r8s9-t0u1-v2w3-x4y5-z6a7-b8c9-d0e1-f2g3',
                'title' => 'Introduction to Algorithms, 3rd Edition',
                'slug' => 'introduction-to-algorithms-3rd-edition',
                'description' => 'The latest edition of the essential text and professional reference, with substantial new material on such topics as VLSI algorithms, quantum algorithms, and others.',
                'short_description' => 'A comprehensive textbook on the design and analysis of algorithms.',
                'author' => 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
                'cover_image' => 'https://g.sdlcdn.com/imgs/k/f/6/INTRODUCTION-TO-ALGORITHMS-by-Thomas-SDL369742066-1-96985.jpg',
                'pdf_file' => '/pdfs/algorithms.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 245,
                'view_count' => 0,
                'read_count' => 1600,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 8, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 4, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'q7r8s9t0-u1v2-w3x4-y5z6-a7b8-c9d0-e1f2-g3h4',
                'title' => 'The Selfish Gene',
                'slug' => 'the-selfish-gene',
                'description' => 'Inheriting the mantle of Richard Dawkins, The Selfish Gene is a classic in evolutionary biology and is considered one of the most important books of the 20th century.',
                'short_description' => 'A revolutionary book on evolution and the gene-centered view of life.',
                'author' => 'Richard Dawkins',
                'cover_image' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1366758096i/61535.jpg',
                'pdf_file' => '/pdfs/selfish-gene.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 312,
                'view_count' => 0,
                'read_count' => 2400,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 9, 3, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'r8s9t0u1-v2w3-x4y5-z6a7-b8c9-d0e1-f2g3-h4i5',
                'title' => 'A Brief History of Time: From the Big Bang to Black Holes',
                'slug' => 'brief-history-of-time',
                'description' => 'From the Big Bang to black holes, from dark matter to a possible Big Crunch, our universe is a fascinating subject. Stephen Hawking explains how it all works in this groundbreaking book.',
                'short_description' => 'From the Big Bang to black holes, a journey through the cosmos.',
                'author' => 'Stephen Hawking',
                'cover_image' => 'https://m.media-amazon.com/images/I/81DBK93b6jL.jpg',
                'pdf_file' => '/pdfs/brief-history-time.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 89,
                'view_count' => 0,
                'read_count' => 80,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 12, 2, 9, 50, 12),
                'created_at' => Carbon::create(2025, 11, 2, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 's9t0u1v2-w3x4-y5z6-a7b8-c9d0-e1f2-g3h4-i5j6',
                'title' => '1984',
                'slug' => '1984-george-orwell',
                'description' => 'Winston Smith toes the line between truth and lies in a dystopian society where Big Brother is always watching and the Thought Police can read your mind.',
                'short_description' => 'A classic dystopian novel about a totalitarian future.',
                'author' => 'George Orwell',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg',
                'pdf_file' => '/pdfs/1984.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 567,
                'view_count' => 0,
                'read_count' => 3800,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 11, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 1, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 't0u1v2w3-x4y5-z6a7-b8c9-d0e1-f2g3-h4i5-j6k7',
                'title' => 'To Kill a Mockingbird',
                'slug' => 'to-kill-a-mockingbird',
                'description' => 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960.',
                'short_description' => 'A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice.',
                'author' => 'Harper Lee',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81aY1lxk+9L.jpg',
                'pdf_file' => '/pdfs/mockingbird.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 489,
                'view_count' => 0,
                'read_count' => 3200,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 28, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 24, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'u1v2w3x4-y5z6-a7b8-c9d0-e1f2-g3h4-i5j6-k7l8',
                'title' => 'The Great Gatsby',
                'slug' => 'the-great-gatsby',
                'description' => 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession".',
                'short_description' => 'A classic American novel set in the Jazz Age.',
                'author' => 'F. Scott Fitzgerald',
                'cover_image' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/512t1zz2t2.jpeg',
                'pdf_file' => '/pdfs/gatsby.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.70,
                'total_reviews' => 345,
                'view_count' => 0,
                'read_count' => 2700,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 23, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 19, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'v2w3x4y5-z6a7-b8c9-d0e1-f2g3-h4i5-j6k7-l8m9',
                'title' => 'Pride and Prejudice',
                'slug' => 'pride-and-prejudice',
                'description' => 'Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work "her own darling child" and its vivacious heroine, Elizabeth Bennet, "as delightful a creature as ever appeared in print."',
                'short_description' => 'A romantic novel of manners written by Jane Austen.',
                'author' => 'Jane Austen',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71Q1tPupKjL.jpg',
                'pdf_file' => '/pdfs/pride-prejudice.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.80,
                'total_reviews' => 412,
                'view_count' => 0,
                'read_count' => 2400,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 18, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 14, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'w3x4y5z6-a7b8-c9d0-e1f2-g3h4-i5j6-k7l8-m9n0',
                'title' => 'The Hobbit, or There and Back Again',
                'slug' => 'the-hobbit',
                'description' => 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day.',
                'short_description' => 'A fantasy novel about the adventures of Bilbo Baggins.',
                'author' => 'J.R.R. Tolkien',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg',
                'pdf_file' => '/pdfs/hobbit.pdf',
                'language' => 'en',
                'status' => 'published',
                'average_rating' => 4.90,
                'total_reviews' => 523,
                'view_count' => 0,
                'read_count' => 3500,
                'creator_id' => $creatorId,
                'category_id' => $categoryId,
                'city_id' => $cityId,
                'published_at' => Carbon::create(2025, 10, 13, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 9, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
        ];

        // Menggunakan insertOrIgnore untuk mencegah error duplikat jika dijalankan ulang
        DB::table('ebooks')->insertOrIgnore($ebooks);

        $this->command->info('Berhasil menambahkan ' . count($ebooks) . ' e-book.');
    }
}
