<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\EbookCategory;
use App\Models\City;
use App\Models\Ebook;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class EbookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ebooks = [
            [
                'id' => '44f72995-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'slug' => 'clean-code-handbook-agile-software-craftsmanship',
                'description' => 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn\'t have to be that way.',
                'short_description' => 'Buku wajib untuk programmer yang ingin menulis kode yang bersih, mudah dipahami, dan mudah di-maintain.',
                'author' => 'Robert C. Martin',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQxdrfnY3jF-G_oCs9EmrBDOptIsqnhJsTzoUBG7ggF7KftSfeVcCtKVt-pRCULCTZPXs&usqp=CAU',
                'content_text' => null,
                'pdf_file' => '/pdfs/clean-code.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 890,
                'average_rating' => 4.80,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 2, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f929d0-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Midnight Library',
                'slug' => '-midnight-library',
                'description' => 'Between life and death there is a library, and within that library, shelves go on forever. Every book provides a chance to try another life you could have lived.',
                'short_description' => 'Novel tentang seorang wanita yang menemukan perpustakaan antara hidup dan mati.',
                'author' => 'Matt Haig',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDyURiRkAyR8M19wt-aAvUy8ZCXXS_z2mv0w&s',
                'content_text' => null,
                'pdf_file' => '/pdfs/midnight-library.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2100,
                'average_rating' => 4.50,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 10, 18, 1, 5, 7),
                'created_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f9495b-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
                'slug' => 'atomic-habits-build-good-habits-break-bad-ones',
                'description' => 'A supremely practical and useful book. James Clear distills the most fundamental information about habit formation, so you can accomplish more by focusing on less.',
                'short_description' => 'Buku tentang membangun kebiasaan kecil yang menghasilkan perubahan besar.',
                'author' => 'James Clear',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg',
                'content_text' => null,
                'pdf_file' => 'https://eprints.upgris.ac.id/385/1/Aku%2C%20Dia%20dan%20Mereka%20Cover%20Full.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 4,
                'read_count' => 3800,
                'average_rating' => 4.90,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 17, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 9, 3, 4, 49),
            ],
            [
                'id' => '44f94d4f-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Pragmatic Programmer: Your Journey to Mastery',
                'slug' => 'pragmatic-programmer-journey-to-mastery',
                'description' => 'This book is for programmers who want to become software craftsmen. This isn\'t just another programming book; it\'s a guide to becoming a better, more pragmatic programmer.',
                'short_description' => 'Panduan untuk menjadi programmer yang pragmatis dan efektif.',
                'author' => 'David Thomas, Andrew Hunt',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/51W1sBPO7tL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/pragmatic-programmer.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 540,
                'average_rating' => 4.70,
                'total_reviews' => 134,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 22, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 23, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f95087-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'description' => 'In this book, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.',
                'short_description' => 'Eksplorasi tentang dua sistem pemikiran manusia.',
                'author' => 'Daniel Kahneman',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/61fdrEuPJwL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/thinking-fast-slow.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1500,
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'created_at' => Carbon::create(2025, 8, 4, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f95374-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Laut Bercerita',
                'slug' => 'laut-bercerita',
                'description' => 'Ketika Dira, seorang aktivis mahasiswa, menghilang secara misterius di tengah gejolak politik masa lalu, keluarganya hanya menerima keheningan sebagai jawaban. Bertahun-tahun kemudian, sang adik, Lira, tumbuh dengan bayang-bayang ketidakpastian. Didorong oleh kenangan dan teka-teki yang tertinggal, Lira memulai pencarian akan kebenaran. Melalui catatan lama, saksi bisu, dan potongan sejarah yang tersembunyi, ia mencoba menyusun kembali jejak sang kakak — dan menghadapi kenyataan pahit tentang negara, keluarga, dan dirinya sendiri.',
                'short_description' => 'Novel masterpiece dari Leila S. Chudori tentang sejarah kelam Indonesia.',
                'author' => 'Leila S. Chudori',
                'cover_image' => 'https://cdn.gramedia.com/uploads/items/9786024246945_Laut-Bercerita.jpg',
                'content_text' => null,
                'pdf_file' => '/images/testing.pdf',
                'language' => 'id',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 13,
                'read_count' => 3200,
                'average_rating' => 4.80,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 8, 4, 1, 5, 7),
                'created_at' => Carbon::create(2025, 6, 5, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 8, 4, 25, 14),
            ],
            [
                'id' => '44f95637-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Pemrograman Python: Dasar hingga Mahir',
                'slug' => 'pemrograman-python-dasar-hingga-mahir',
                'description' => 'Buku komprehensif untuk belajar Python dari dasar hingga tingkat lanjut dengan contoh praktis.',
                'short_description' => 'Buku wajib untuk belajar Python dengan pendekatan praktis.',
                'author' => 'Budi Raharjo',
                'cover_image' => 'https://cdn.gramedia.com/uploads/products/lnl19y9apu.jpg',
                'content_text' => 'Buku ini mengajarkan Python dari konsep dasar hingga pembuatan aplikasi real.',
                'pdf_file' => '/pdfs/python-pemrograman.pdf',
                'language' => 'id',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2100,
                'average_rating' => 4.50,
                'total_reviews' => 234,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 12, 1, 5, 7),
                'created_at' => Carbon::create(2025, 10, 13, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96603-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'A Brief History of Time',
                'slug' => 'a-brief-history-of-time',
                'description' => 'From the Big Bang to Black Holes, Stephen Hawking explains the universe in a way that is accessible to everyone.',
                'short_description' => 'Perjalanan melalui kosmos dari salah satu pemikir terbesar abad kita.',
                'author' => 'Stephen Hawking',
                'cover_image' => 'https://m.media-amazon.com/images/I/81DBK93b6jL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/brief-history-time.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 80,
                'average_rating' => 4.70,
                'total_reviews' => 89,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 9, 50, 12),
                'created_at' => Carbon::create(2025, 11, 2, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96951-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'Digital Marketing Fundamentals',
                'slug' => 'digital-marketing-fundamentals',
                'description' => 'Learn the basics of digital marketing in the modern era. SEO, Social Media, Content Marketing, and more.',
                'short_description' => 'Panduan dasar digital marketing untuk pemula.',
                'author' => 'Marketing Team',
                'cover_image' => 'https://i0.wp.com/minhajpustaka.id/wp-content/uploads/2025/05/COVER-4-scaled.png?fit=1729%2C2560&ssl=1',
                'content_text' => 'Full content available in text format.',
                'pdf_file' => null,
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.40,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 11, 27, 1, 5, 7),
                'created_at' => Carbon::create(2025, 11, 17, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => '44f96c10-cee0-11f0-b8a8-745d2258e25c',
                'title' => 'The Design of Everyday Things',
                'slug' => 'design-everyday-things',
                'description' => 'Even the smartest among us can feel inept as we fail to figure out which light switch or oven burner to turn on.',
                'short_description' => 'Buku klasik tentang design dan user experience.',
                'author' => 'Don Norman',
                'cover_image' => 'https://m.media-amazon.com/images/I/71sF8kuMW3L._AC_UF1000,1000_QL80_.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/design-everyday-things.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1200,
                'average_rating' => 4.60,
                'total_reviews' => 156,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 10, 3, 1, 5, 7),
                'created_at' => Carbon::create(2025, 9, 3, 1, 5, 7),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab38443d-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Eloquent JavaScript',
                'slug' => 'eloquent-javascript',
                'description' => 'A modern introduction to programming with JavaScript.',
                'short_description' => 'Buku JavaScript terbaik untuk pemula hingga mahir.',
                'author' => 'Marijn Haverbeke',
                'cover_image' => 'https://eloquentjavascript.net/img/cover.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/eloquent-js.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1200,
                'average_rating' => 4.70,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 27, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44ac4f-cf2e-11f0-9073-745d2258e25c',
                'title' => 'You Don\'t Know JS Yet',
                'slug' => 'you-dont-know-js-yet',
                'description' => 'Deep dive into JavaScript core mechanisms.',
                'short_description' => 'Seri lengkap pengenalan mendalam JavaScript.',
                'author' => 'Kyle Simpson',
                'cover_image' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1585414018i/52764087.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/ydkjs.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1800,
                'average_rating' => 4.80,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 22, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44b4bc-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Clean Coder',
                'slug' => '-clean-coder',
                'description' => 'A code of conduct for professional programmers.',
                'short_description' => 'Panduan menjadi programmer profesional.',
                'author' => 'Robert C. Martin',
                'cover_image' => 'https://m.media-amazon.com/images/I/51RjrmLJv0L.__AC_SR166,182___.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/clean-coder.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 650,
                'average_rating' => 4.60,
                'total_reviews' => 123,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 17, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44b872-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Design Patterns: Elements of Reusable Object-Oriented Software',
                'slug' => 'design-patterns',
                'description' => 'The classic book on design patterns.',
                'short_description' => 'Buku klasik tentang design patterns.',
                'author' => 'Erich Gamma',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/51szD9HC9pL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/design-patterns.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 900,
                'average_rating' => 4.90,
                'total_reviews' => 267,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 12, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44bb0c-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Refactoring: Improving the Design of Existing Code',
                'slug' => 'refactoring-improving-design',
                'description' => 'How to improve existing code structure.',
                'short_description' => 'Teknik refactoring untuk kode yang lebih baik.',
                'author' => 'Martin Fowler',
                'cover_image' => 'https://m.media-amazon.com/images/I/71vEr0oyt-L._AC_UF1000,1000_QL80_.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/refactoring.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 720,
                'average_rating' => 4.70,
                'total_reviews' => 156,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 7, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44bf32-cf2e-11f0-9073-745d2258e25c',
                'title' => '1984',
                'slug' => '1984-george-orwell',
                'description' => 'Classic dystopian novel by George Orwell.',
                'short_description' => 'Novel dystopian klasik tentang masa depan.',
                'author' => 'George Orwell',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/1984.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.80,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 11, 2, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c21c-cf2e-11f0-9073-745d2258e25c',
                'title' => 'To Kill a Mockingbird',
                'slug' => 'to-kill-a-mockingbird',
                'description' => 'Pulitzer Prize-winning novel.',
                'short_description' => 'Novel pemenang Pulitzer Prize.',
                'author' => 'Harper Lee',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81aY1lxk+9L.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/mockingbird.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3200,
                'average_rating' => 4.90,
                'total_reviews' => 489,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 28, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c4df-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Great Gatsby',
                'slug' => '-great-gatsby',
                'description' => 'American classic novel.',
                'short_description' => 'Klasik sastra Amerika.',
                'author' => 'F. Scott Fitzgerald',
                'cover_image' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/512t1zz2t2.jpeg',
                'content_text' => null,
                'pdf_file' => '/pdfs/gatsby.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2700,
                'average_rating' => 4.70,
                'total_reviews' => 345,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 23, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c748-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Pride and Prejudice',
                'slug' => 'pride-and-prejudice',
                'description' => 'Romantic novel of manners.',
                'short_description' => 'Novel romantis klasik.',
                'author' => 'Jane Austen',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71Q1tPupKjL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/pride-prejudice.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2400,
                'average_rating' => 4.80,
                'total_reviews' => 412,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 18, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44c9d3-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Hobbit',
                'slug' => '-hobbit',
                'description' => 'Fantasy novel by J.R.R. Tolkien.',
                'short_description' => 'Novel fantasi petualangan Bilbo Baggins.',
                'author' => 'J.R.R. Tolkien',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/hobbit.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3500,
                'average_rating' => 4.90,
                'total_reviews' => 523,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 13, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44ce24-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Rich Dad Poor Dad',
                'slug' => 'rich-dad-poor-dad',
                'description' => 'Financial literacy and independence.',
                'short_description' => 'Mengubah mindset tentang uang dan investasi.',
                'author' => 'Robert Kiyosaki',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/rich-dad.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4500,
                'average_rating' => 4.60,
                'total_reviews' => 678,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 8, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d0f6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The 7 Habits of Highly Effective People',
                'slug' => '7-habits-highly-effective-people',
                'description' => 'Personal and professional effectiveness.',
                'short_description' => '7 kebiasaan orang-orang efektif.',
                'author' => 'Stephen R. Covey',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp4yXo-iLBeG2yNDazs9yS9VxZh-xB8N1FJA&s',
                'content_text' => null,
                'pdf_file' => '/pdfs/7-habits.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4200,
                'average_rating' => 4.70,
                'total_reviews' => 567,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 10, 3, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d460-cf2e-11f0-9073-745d2258e25c',
                'title' => 'How to Win Friends and Influence People',
                'slug' => 'how-to-win-friends',
                'description' => 'Self-help book about social skills.',
                'short_description' => 'Cara berhubungan dengan orang lain.',
                'author' => 'Dale Carnegie',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71tbalAHYCL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/win-friends.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 4800,
                'average_rating' => 4.80,
                'total_reviews' => 612,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 28, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d6ec-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'slug' => 'subtle-art-not-giving-fck',
                'description' => 'Counterintuitive approach to living.',
                'short_description' => 'Pendekatan hidup yang berbeda.',
                'author' => 'Mark Manson',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/subtle-art.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 5400,
                'average_rating' => 4.50,
                'total_reviews' => 734,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 23, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44d97e-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Deep Work: Rules for Focused Success',
                'slug' => 'deep-work',
                'description' => 'Rules for focused success in a distracted world.',
                'short_description' => 'Cara fokus di dunia yang penuh gangguan.',
                'author' => 'Cal Newport',
                'cover_image' => 'https://m.media-amazon.com/images/I/61zt25yYrCL._AC_UF1000,1000_QL80_.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/deep-work.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2900,
                'average_rating' => 4.60,
                'total_reviews' => 289,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 18, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44faf6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Mythical Man-Month',
                'slug' => 'mythical-man-month',
                'description' => 'Essays on software engineering.',
                'short_description' => 'Esai tentang engineering software.',
                'author' => 'Fred Brooks',
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/f/fd/Mythical_man-month_%28book_cover%29.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/mythical-man-month.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1400,
                'average_rating' => 4.80,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 13, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab44fe95-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Introduction to Algorithms',
                'slug' => 'introduction-algorithms',
                'description' => 'Comprehensive textbook on algorithms.',
                'short_description' => 'Buku lengkap tentang algoritma.',
                'author' => 'Thomas H. Cormen',
                'cover_image' => 'https://g.sdlcdn.com/imgs/k/f/6/INTRODUCTION-TO-ALGORITHMS-by-Thomas-SDL369742066-1-96985.jpg?trim=10&w=590&h=695&sharp=7',
                'content_text' => null,
                'pdf_file' => '/pdfs/algorithms.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 1600,
                'average_rating' => 4.90,
                'total_reviews' => 245,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 8, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450121-cf2e-11f0-9073-745d2258e25c',
                'title' => 'The Selfish Gene',
                'slug' => 'selfish-gene',
                'description' => 'Evolutionary biology book.',
                'short_description' => 'Buku biologi evolusioner.',
                'author' => 'Richard Dawkins',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWB8iSQM-xjsx7o5YOu8k2CPOCdCIdnz2IIA&s',
                'content_text' => null,
                'pdf_file' => '/pdfs/selfish-gene.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2400,
                'average_rating' => 4.70,
                'total_reviews' => 312,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 9, 3, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4503f6-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Sapiens: A Brief History of Humankind',
                'slug' => 'sapiens-brief-history-humankind',
                'description' => 'History of the human species.',
                'short_description' => 'Sejarah spesies manusia.',
                'author' => 'Yuval Noah Harari',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/sapiens.pdf',
                'language' => 'en',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 5900,
                'average_rating' => 4.80,
                'total_reviews' => 789,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 29, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab45069e-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Cosmos',
                'slug' => 'cosmos',
                'description' => 'Popular science book about the universe.',
                'short_description' => 'Buku sains populer tentang alam semesta.',
                'author' => 'Carl Sagan',
                'cover_image' => 'https://m.media-amazon.com/images/I/51SX54fcT-L._AC_UF1000,1000_QL80_.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/cosmos.pdf',
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2700,
                'average_rating' => 4.90,
                'total_reviews' => 412,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 24, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450945-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Ronggeng Dukuh Paruk',
                'slug' => 'ronggeng-dukuh-paruk',
                'description' => 'Novel karya Ahmad Tohari.',
                'short_description' => 'Kisah tentang kehidupan penari ronggeng.',
                'author' => 'Ahmad Tohari',
                'cover_image' => 'https://ebooks.gramedia.com/ebook-covers/53333/image_highres/BLK_RDP2020706247.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/ronggeng-dukuh-paruk.pdf',
                'language' => 'id',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 2800,
                'average_rating' => 4.70,
                'total_reviews' => 234,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 19, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450bba-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Negeri 5 Menara',
                'slug' => 'negeri-5-menara',
                'description' => 'Novel inspiratif tentang pesantren.',
                'short_description' => 'Kisah inspiratif kehidupan pesantren.',
                'author' => 'Ahmad Fuadi',
                'cover_image' => 'https://assets-a1.kompasiana.com/items/album/2015/08/15/foto-55cf1f2ec423bd1608ecc805.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/negeri-5-menara.pdf',
                'language' => 'id',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3900,
                'average_rating' => 4.80,
                'total_reviews' => 345,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 14, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab450e38-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Laskar Pelangi',
                'slug' => 'laskar-pelangi',
                'description' => 'Novel karya Andrea Hirata.',
                'short_description' => 'Kisah tentang pendidikan dan persahabatan.',
                'author' => 'Andrea Hirata',
                'cover_image' => 'https://simpus.mkri.id/uploaded_files/sampul_koleksi/original/Monograf//uploadedfiles/perpustakaan/11610-11613.jpg',
                'content_text' => null,
                'pdf_file' => '/pdfs/laskar-pelangi.pdf',
                'language' => 'id',
                'is_featured' => 1,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 6800,
                'average_rating' => 4.90,
                'total_reviews' => 890,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 9, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4513ef-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Web Development Basics',
                'slug' => 'web-development-basics',
                'description' => 'Introduction to web development.',
                'short_description' => 'Pengantar dasar web development.',
                'author' => 'Web Team',
                'cover_image' => 'https://m.media-amazon.com/images/I/61E2+k4+uRL._AC_UF1000,1000_QL80_.jpg',
                'content_text' => 'Full HTML, CSS, JavaScript content.',
                'pdf_file' => null,
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3800,
                'average_rating' => 4.40,
                'total_reviews' => 189,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 8, 4, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
            [
                'id' => 'ab4516f0-cf2e-11f0-9073-745d2258e25c',
                'title' => 'Data Science Fundamentals',
                'slug' => 'data-science-fundamentals',
                'description' => 'Introduction to data science.',
                'short_description' => 'Dasar-dasar data science untuk pemula.',
                'author' => 'Data Team',
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTiQWQgvVsTlfLIikfL74aQnQsS5MGlCvL1A&s',
                'content_text' => 'Python, statistics, machine learning basics.',
                'pdf_file' => null,
                'language' => 'en',
                'is_featured' => 0,
                'status' => 'published',
                'view_count' => 0,
                'read_count' => 3400,
                'average_rating' => 4.50,
                'total_reviews' => 167,
                'creator_id' => null,
                'published_at' => Carbon::create(2025, 12, 2, 10, 26, 19),
                'created_at' => Carbon::create(2025, 7, 30, 10, 26, 19),
                'updated_at' => Carbon::create(2025, 12, 7, 14, 7, 38),
            ],
        ];

        // Menggunakan insertOrIgnore untuk mencegah error duplikat jika dijalankan ulang
        DB::table('ebooks')->insertOrIgnore($ebooks);

        $this->command->info('Berhasil menambahkan ' . count($ebooks) . ' e-book.');
    }
}
